### ISSUE TITLE
Erro ao atualizar imóvel residencial

### ISSUE THREAD

**Issue by RonaldCamp** [victorl2/gold-star-backend#51]
**Cenário:** Atualizar um imóvel residencial que possui ao menos 1 processo cadastrado ou moradores.
**Desfecho:** A atualização não acontece;

_**Como reproduzir:** Procure o imóvel residencial 1037 ( na base de dados padrão ) e tente cadastrar um locatário_

**Comment by victorl2** [comment]
Existem alguns detalhes estruturais no backend, porém abrir uma nova transação ao buscar um locatário contorna o problema.
